src/Buecherei.cpp File Reference
#include <iostream>
#include <string>
#include <vector>
#include "Medium.h"
#include "Datum.h"
Macros
#define UNTERKLASSENVORHANDEN true
Functions
void fuelleDatenbank (std::vector< Medium * > &medien)
void mediumHinzufuegen (std::vector< Medium * > &medien)
void mediumEntfernen (std::vector< Medium * > &medien)
void mediumAusleihen (std::vector< Medium * > &medien, Datum aktuellesDatum)
void mediumZurueckgeben (std::vector< Medium * > &medien)
void alleMedienAusgeben (std::vector< Medium * > &medien)
void ausgelieheneMedienAusgeben (const std::vector< Medium * > &medien)
int main ()
Macro Definition Documentation
UNTERKLASSENVORHANDEN
#define UNTERKLASSENVORHANDEN true
Praktikum Informatik 1 MMXXV
@ file Buecherei.cpp
Definition at line 20 of file Buecherei.cpp.
Function Documentation
alleMedienAusgeben()
void alleMedienAusgeben (std::vector< Medium * > & medien)
Definition at line 414 of file Buecherei.cpp.
Referenced by main().
ausgelieheneMedienAusgeben()
void ausgelieheneMedienAusgeben (const std::vector< Medium * > & medien)
Definition at line 429 of file Buecherei.cpp.
Referenced by main().
fuelleDatenbank()
void fuelleDatenbank (std::vector< Medium * > & medien)
Definition at line 164 of file Buecherei.cpp.
Referenced by main().
main()
int main ()
Definition at line 51 of file Buecherei.cpp.
References alleMedienAusgeben(), ausgelieheneMedienAusgeben(), fuelleDatenbank(), mediumAusleihen(), mediumEntfernen(), mediumHinzufuegen(), and mediumZurueckgeben().
mediumAusleihen()
void mediumAusleihen (std::vector< Medium * > & medien, Datum aktuellesDatum)
Definition at line 345 of file Buecherei.cpp.
Referenced by main().
mediumEntfernen()
void mediumEntfernen (std::vector< Medium * > & medien)
Definition at line 313 of file Buecherei.cpp.
Referenced by main().
mediumHinzufuegen()
void mediumHinzufuegen (std::vector< Medium * > & medien)
Definition at line 205 of file Buecherei.cpp.
Referenced by main().
mediumZurueckgeben()
void mediumZurueckgeben (std::vector< Medium * > & medien)
Definition at line 386 of file Buecherei.cpp.
Referenced by main().