Magazin Class Reference
Klasse Magazin, abgeleitet von Medium.
#include <Magazin.h>
Public Member Functions
Magazin (std::string initTitel, Datum initDatumAusgabe, std::string initSparte)
Konstruktor.
virtual ~Magazin ()
Destruktor.
virtual void ausgabe () const override
Gibt alle Informationen des Magazins aus.
virtual bool ausleihen (Person person, Datum ausleihdatum) override
Prüft, ob das Magazin ausgeliehen werden darf.
Public Member Functions inherited from Medium
Medium (std::string initTitel)
Konstruktor.
virtual ~Medium (void)
virtueller Destruktor
void zurueckgeben ()
Gibt ein Medium in die Bcherei zurck.
unsigned int getID ()
ID des Mediums.
bool istAusgeliehen () const
Status des Mediums.
Private Attributes
Datum datumAusgabe
Erscheinungsdatum der Ausgabe.
std::string sparte
Sparte des Magazins.
Additional Inherited Members
Protected Attributes inherited from Medium
unsigned int ID
Eindeutige ID des Mediums.
std::string titel
Titel des Mediums.
bool status
Status des Mediums (true: ausgeliehen, false: nicht ausgeliehen)
Datum datumAusgeliehen
Datum seit dem das Medium ausgeliehen ist.
Person personAusgeliehen
Person, die das Medium ausgeliehen hat.
Static Protected Attributes inherited from Medium
static unsigned int currentID = 1
Statische Variable zum Erzeugen der fortlaufenden IDs.
Detailed Description
Klasse Magazin, abgeleitet von Medium.
Speichert zusätzlich zum Titel das Erscheinungsdatum und die Sparte.
Definition at line 18 of file Magazin.h.
Constructor & Destructor Documentation
Magazin()
Magazin::Magazin (std::string initTitel, Datum initDatumAusgabe, std::string initSparte)
Konstruktor.
Parameters
initTitel Titel des Magazins
initDatumAusgabe Erscheinungsdatum der Ausgabe
initSparte Sparte des Magazins
Definition at line 4 of file Magazin.cpp.
References datumAusgabe, Medium::Medium(), and sparte.
~Magazin()
Magazin::~Magazin () [virtual]
Destruktor.
Definition at line 9 of file Magazin.cpp.
Member Function Documentation
ausgabe()
void Magazin::ausgabe () const [override], [virtual]
Gibt alle Informationen des Magazins aus.
Implements Medium.
Definition at line 11 of file Magazin.cpp.
References Medium::ausgabe(), datumAusgabe, and sparte.
ausleihen()
bool Magazin::ausleihen (Person person, Datum ausleihdatum) [override], [virtual]
Prüft, ob das Magazin ausgeliehen werden darf.
Parameters
person Die ausleihende Person
ausleihdatum Das Ausleihdatum
Returns
true, wenn das Magazin nicht die neueste Ausgabe ist, sonst false
Reimplemented from Medium.
Definition at line 20 of file Magazin.cpp.
References Medium::ausleihen(), datumAusgabe, Datum::getJahr(), and Datum::getMonat().
Member Data Documentation
datumAusgabe
Datum Magazin::datumAusgabe [private]
Erscheinungsdatum der Ausgabe.
Definition at line 48 of file Magazin.h.
Referenced by ausgabe(), ausleihen(), and Magazin().
sparte
std::string Magazin::sparte [private]
Sparte des Magazins.
Definition at line 49 of file Magazin.h.
Referenced by ausgabe(), and Magazin().
The documentation for this class was generated from the following files:
src/Magazin.h
src/Magazin.cpp