Medium Class Reference
Basisklasse fr smtliche Medien.
#include <Medium.h>
Public Member Functions
Medium (std::string initTitel)
Konstruktor.
virtual ~Medium (void)
virtueller Destruktor
virtual void ausgabe () const =0
Ausgabefunktion.
virtual bool ausleihen (Person person, Datum ausleihdatum)
Ausleihen-Funktion.
void zurueckgeben ()
Gibt ein Medium in die Bcherei zurck.
unsigned int getID ()
ID des Mediums.
bool istAusgeliehen () const
Status des Mediums.
Protected Attributes
unsigned int ID
Eindeutige ID des Mediums.
std::string titel
Titel des Mediums.
bool status
Status des Mediums (true: ausgeliehen, false: nicht ausgeliehen)
Datum datumAusgeliehen
Datum seit dem das Medium ausgeliehen ist.
Person personAusgeliehen
Person, die das Medium ausgeliehen hat.
Static Protected Attributes
static unsigned int currentID = 1
Statische Variable zum Erzeugen der fortlaufenden IDs.
Detailed Description
Basisklasse fr smtliche Medien.
Diese Klasse stellt eine Basisklasse fr Objekte dar, die Medien beschreiben Von dieser Klasse werden alle anderen Medien, wie z.B. Buch oder DVD abgeleitet
Definition at line 19 of file Medium.h.
Constructor & Destructor Documentation
Medium()
Medium::Medium (std::string initTitel)
Konstruktor.
Konstruktor der Klasse Medium
Parameters
std::string initTitel: Titel des Mediums
Definition at line 15 of file Medium.cpp.
References currentID, ID, status, and titel.
Referenced by Buch::Buch(), DVD::DVD(), and Magazin::Magazin().
~Medium()
Medium::~Medium (void) [virtual]
virtueller Destruktor
Definition at line 21 of file Medium.cpp.
Member Function Documentation
ausgabe()
void Medium::ausgabe () const [pure virtual]
Ausgabefunktion.
Funktion gibt alle Informationen eines Mediums auf der Konsole aus
Implemented in Buch, DVD, and Magazin.
Definition at line 25 of file Medium.cpp.
References datumAusgeliehen, ID, personAusgeliehen, status, and titel.
Referenced by Buch::ausgabe(), DVD::ausgabe(), Magazin::ausgabe(), and operator<<().
ausleihen()
bool Medium::ausleihen (Person person, Datum ausleihdatum) [virtual]
Ausleihen-Funktion.
Parameters
Person person: Person die das Medium ausleihen mchte
Datum ausleihdatum: Datum an dem das Medium ausgeliehen wird
Returns
bool: true, wenn die Ausleihbeschrnkungen erfllt sind und das Medium ausgeliehen werden kann false, wenn die Ausleihbeschrnkungen nicht erfllt sind und das Medium nicht ausgeliehen werden kann
Reimplemented in DVD, and Magazin.
Definition at line 40 of file Medium.cpp.
References datumAusgeliehen, Person::getName(), personAusgeliehen, status, and titel.
Referenced by DVD::ausleihen(), and Magazin::ausleihen().
getID()
unsigned int Medium::getID ()
ID des Mediums.
Returns
int: gibt die ID des Mediums zurck
Definition at line 76 of file Medium.cpp.
References ID.
istAusgeliehen()
bool Medium::istAusgeliehen () const [inline]
Status des Mediums.
Returns
std::string: gibt den Titel des Mediums zurck
Definition at line 72 of file Medium.h.
References status.
zurueckgeben()
void Medium::zurueckgeben ()
Gibt ein Medium in die Bcherei zurck.
Definition at line 57 of file Medium.cpp.
References status, and titel.
Member Data Documentation
currentID
unsigned int Medium::currentID = 1 [static], [protected]
Statische Variable zum Erzeugen der fortlaufenden IDs.
Definition at line 78 of file Medium.h.
Referenced by Medium().
datumAusgeliehen
Datum Medium::datumAusgeliehen [protected]
Datum seit dem das Medium ausgeliehen ist.
Definition at line 98 of file Medium.h.
Referenced by ausgabe(), and ausleihen().
ID
unsigned int Medium::ID [protected]
Eindeutige ID des Mediums.
Definition at line 83 of file Medium.h.
Referenced by ausgabe(), getID(), and Medium().
personAusgeliehen
Person Medium::personAusgeliehen [protected]
Person, die das Medium ausgeliehen hat.
Definition at line 103 of file Medium.h.
Referenced by ausgabe(), and ausleihen().
status
bool Medium::status [protected]
Status des Mediums (true: ausgeliehen, false: nicht ausgeliehen)
Definition at line 93 of file Medium.h.
Referenced by ausgabe(), ausleihen(), istAusgeliehen(), Medium(), and zurueckgeben().
titel
std::string Medium::titel [protected]
Titel des Mediums.
Definition at line 88 of file Medium.h.
Referenced by ausgabe(), ausleihen(), Medium(), and zurueckgeben().
The documentation for this class was generated from the following files:
src/Medium.h
src/Medium.cpp