Datum Class Reference
Klasse fr ein Datum.
#include <Datum.h>
Public Member Functions
Datum ()
Standartkonstruktor.
Datum (int initTag, int initMonat, int initJahr)
Konstruktor fr ein gegebenes Datum.
~Datum (void)
int getTag () const
Getters auf die Attribute der Klasse Datum.
int getMonat () const
int getJahr () const
void eingabe (std::istream &in)
Eingabe eines Datums ber einen Eingabestream.
void ausgabe (std::ostream &out) const
Ausgabe eines Datums ber einen Ausgabestream.
Datum & operator= (Datum &d)
Zuweisungsoperator.
int operator- (const Datum d) const
Subtraktionsoperator.
Datum operator+ (const int anzahlTage) const
Additionsoperator.
Private Attributes
int tag
int monat
int jahr
Static Private Attributes
static const int tageMonat [12] = {31, 30, 31, 28, 31, 30, 31, 31, 30, 31, 30, 31}
Enthlt die Anzahl der Tage pro Monat.
Detailed Description
Klasse fr ein Datum.
Speichert ein Datum, bestehend aus Tag, Monat und Jahr. Die Klasse Datum bietet verschiedene Funktionalitten/Operatoren die zum Ausgeben/Bearbeiten/Vergleichen von verschiedenen Daten genutzt werden knnen
Definition at line 21 of file Datum.h.
Constructor & Destructor Documentation
Datum() [1/2]
Datum::Datum ()
Standartkonstruktor.
Initialisiert die Klasse Datum mit dem heutigen Datum
Definition at line 16 of file Datum.cpp.
References jahr, monat, and tag.
Referenced by operator+(), operator-(), and operator=().
Datum() [2/2]
Datum::Datum (int initTag, int initMonat, int initJahr)
Konstruktor fr ein gegebenes Datum.
Parameters
int initTag: gegebener Tag
int initMonat: gegebener Monat
int initJahr: gegebenes Jahr
Definition at line 32 of file Datum.cpp.
References jahr, monat, and tag.
~Datum()
Datum::~Datum (void)
@Brief Destruktor
Definition at line 38 of file Datum.cpp.
Member Function Documentation
ausgabe()
void Datum::ausgabe (std::ostream & out) const
Ausgabe eines Datums ber einen Ausgabestream.
Parameters
std::ostream out: Ausgabestream zum Ausgeben
Definition at line 43 of file Datum.cpp.
References jahr, monat, and tag.
Referenced by operator<<().
eingabe()
void Datum::eingabe (std::istream & in)
Eingabe eines Datums ber einen Eingabestream.
Parameters
std::istream& in: Eingabestream zum Einlesen
Definition at line 57 of file Datum.cpp.
References jahr, monat, tag, and tageMonat.
Referenced by operator>>().
getJahr()
int Datum::getJahr () const [inline]
Definition at line 54 of file Datum.h.
References jahr.
Referenced by DVD::ausleihen(), and Magazin::ausleihen().
getMonat()
int Datum::getMonat () const [inline]
Definition at line 53 of file Datum.h.
References monat.
Referenced by DVD::ausleihen(), and Magazin::ausleihen().
getTag()
int Datum::getTag () const [inline]
Getters auf die Attribute der Klasse Datum.
Returns
int: Gibt den Tag, Monat oder das Jahr des Datums zurueck
Definition at line 52 of file Datum.h.
References tag.
Referenced by DVD::ausleihen().
operator+()
Datum Datum::operator+ (const int anzahlTage) const
Additionsoperator.
Parameters
const int: anzahlTag Anzahl der Tage, die auf das aktuelle Datum addiert werden sollen
Returns
Datum: Gibt das modifizierte Datum zurck
Definition at line 142 of file Datum.cpp.
References Datum(), jahr, monat, tag, and tageMonat.
operator-()
int Datum::operator- (const Datum d) const
Subtraktionsoperator.
Parameters
Datum& d: Argument auf der rechten Seite
Returns
int: Gibt die Differenz der beiden Monate in Monaten zurck
Definition at line 126 of file Datum.cpp.
References Datum(), jahr, monat, and tag.
operator=()
Datum & Datum::operator= (Datum & d)
Zuweisungsoperator.
Parameters
Datum& d: Argument auf der rechten Seite, welches der Ausgangspunkt fr die Zuweisung ist
Definition at line 166 of file Datum.cpp.
References Datum(), jahr, monat, and tag.
Member Data Documentation
jahr
int Datum::jahr [private]
Definition at line 98 of file Datum.h.
Referenced by ausgabe(), Datum(), Datum(), eingabe(), getJahr(), operator+(), operator-(), and operator=().
monat
int Datum::monat [private]
Definition at line 97 of file Datum.h.
Referenced by ausgabe(), Datum(), Datum(), eingabe(), getMonat(), operator+(), operator-(), and operator=().
tag
int Datum::tag [private]
Definition at line 96 of file Datum.h.
Referenced by ausgabe(), Datum(), Datum(), eingabe(), getTag(), operator+(), operator-(), and operator=().
tageMonat
const int Datum::tageMonat = {31, 30, 31, 28, 31, 30, 31, 31, 30, 31, 30, 31} [static], [private]
Enthlt die Anzahl der Tage pro Monat.
Definition at line 13 of file Datum.h.
Referenced by eingabe(), and operator+().
The documentation for this class was generated from the following files:
src/Datum.h
src/Datum.cpp