DVD Class Reference
Klasse DVD, abgeleitet von Medium.
#include <DVD.h>
Public Member Functions
DVD (std::string initTitel, int initAltersfreigabe, std::string initGenre)
Konstruktor.
virtual ~DVD ()
Destruktor.
virtual void ausgabe () const override
Gibt alle Informationen der DVD aus.
virtual bool ausleihen (Person person, Datum ausleihdatum) override
Pr체ft, ob die DVD ausgeliehen werden darf.
Public Member Functions inherited from Medium
Medium (std::string initTitel)
Konstruktor.
virtual ~Medium (void)
virtueller Destruktor
void zurueckgeben ()
Gibt ein Medium in die Bcherei zurck.
unsigned int getID ()
ID des Mediums.
bool istAusgeliehen () const
Status des Mediums.
Private Attributes
int altersfreigabe
Altersfreigabe der DVD.
std::string genre
Genre der DVD.
Additional Inherited Members
Protected Attributes inherited from Medium
unsigned int ID
Eindeutige ID des Mediums.
std::string titel
Titel des Mediums.
bool status
Status des Mediums (true: ausgeliehen, false: nicht ausgeliehen)
Datum datumAusgeliehen
Datum seit dem das Medium ausgeliehen ist.
Person personAusgeliehen
Person, die das Medium ausgeliehen hat.
Static Protected Attributes inherited from Medium
static unsigned int currentID = 1
Statische Variable zum Erzeugen der fortlaufenden IDs.
Detailed Description
Klasse DVD, abgeleitet von Medium.
Speichert zus채tzlich zum Titel die Altersfreigabe und das Genre.
Definition at line 17 of file DVD.h.
Constructor & Destructor Documentation
DVD()
DVD::DVD (std::string initTitel, int initAltersfreigabe, std::string initGenre)
Konstruktor.
Parameters
initTitel Titel der DVD
initAltersfreigabe Altersfreigabe der DVD
initGenre Genre der DVD
Definition at line 4 of file DVD.cpp.
References altersfreigabe, genre, and Medium::Medium().
~DVD()
DVD::~DVD () [virtual]
Destruktor.
Definition at line 9 of file DVD.cpp.
Member Function Documentation
ausgabe()
void DVD::ausgabe () const [override], [virtual]
Gibt alle Informationen der DVD aus.
Implements Medium.
Definition at line 11 of file DVD.cpp.
References altersfreigabe, Medium::ausgabe(), and genre.
ausleihen()
bool DVD::ausleihen (Person person, Datum ausleihdatum) [override], [virtual]
Pr체ft, ob die DVD ausgeliehen werden darf.
Parameters
person Die ausleihende Person
ausleihdatum Das Ausleihdatum
Returns
true, wenn die Altersfreigabe erf체llt ist, sonst false
Reimplemented from Medium.
Definition at line 18 of file DVD.cpp.
References altersfreigabe, Medium::ausleihen(), Person::getGeburtsdatum(), Datum::getJahr(), Datum::getMonat(), and Datum::getTag().
Member Data Documentation
altersfreigabe
int DVD::altersfreigabe [private]
Altersfreigabe der DVD.
Definition at line 47 of file DVD.h.
Referenced by ausgabe(), ausleihen(), and DVD().
genre
std::string DVD::genre [private]
Genre der DVD.
Definition at line 48 of file DVD.h.
Referenced by ausgabe(), and DVD().
The documentation for this class was generated from the following files:
src/DVD.h
src/DVD.cpp